language: node_js
node_js:
  - 12 # LTS
  - 13 # latest

script:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./storybook-static
  on:
    branch: master
